### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by BigArty** [imjustleaving/trueNAS#6]
I found this awesome article about setup of trueNAS as a media server, but it appears, that half of the images are not loading. The most important of them is the first settings image of qbit setup. The information there is not duplicated by text....

**Comment by serversathome-personal** [comment]
github has been weird lately about this article. i dont know what the deal is. in order to make sure i can maintain the integrity of the article, i am moving it to a self-hosted wiki (on my truenas box of course). you can find it [here](https://wiki.hydrology.cc). i have not finished doing the import yet so not all articles are up, but keep an eye on it as i plan to finish it this week...

**Comment by serversathome-personal** [comment]
updating the link to avoid login:

[new link to wiki](https://wiki.hydrology.cc/en/home
)
