### ISSUE TITLE
A Section to the guide on removing torrents after the reached a certain point 

### ISSUE THREAD

**Issue by ghost** [imjustleaving/trueNAS#8]
A Section to the guide on removing torrents after the reached a certain point 
such as ratio
time or just once they have been imported to save space and not have duplicate files

**Comment by serversathome-personal** [comment]
the info on removing torrents after a certain time/ratio can be found here https://wiki.servarr.com/prowlarr/indexers right above the section for Adding a custom YML definition. 

the files are not duplicated if the folder structure is built the way i describe in the wiki. see the "hardlinks" section of trash guides for more info https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/

i will not include this info on the wiki due to the fact that i do not want to talk about indexers specifically to avoid legal issues. its a section which is left intentionally ambiguous.
